[package]
name = "init"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
hyperlane = "4.94.0"
app = { workspace = true }
config = { workspace = true }
plugin = { workspace = true }
utils = { workspace = true }
