[package]
name = "app_service"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
hyperlane.workspace = true
config.workspace = true
plugin.workspace = true
utils.workspace = true
