[package]
name = "hyperlane-quick-start"
version = "1.0.1"
edition = "2024"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = """Hyperlane is a lightweight and high-performance Rust HTTP server library designed to simplify network service development. It supports HTTP request parsing, response building, and TCP communication, making it ideal for building modern web services. Additionally, it provides support for request and response middleware, WebSocket, and Server-Sent Events (SSE), enabling flexible and efficient real-time communication. Built with pure Rust and standard library, Hyperlane offers true cross-platform compatibility across Windows, Linux and macOS, with the same API experience on all platforms, powered by Tokio's async runtime for seamless networking without platform-specific dependencies."""
keywords = ["http", "request", "response", "tcp", "cross-platform"]
repository = "https://github.com/ltpp-universe/hyperlane-quick-start.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "logs",
    ".github",
    "**/*.pid",
    "**/*.log",
    "logs"
]

[workspace]
members = [
    "app/*",    
    "config/*",
    "init/*",
    "plugin/*"
]

[workspace.dependencies]
hyperlane = { path = "../hyperlane" }
app_aspect = { path = "app/aspect" }
app_controller = { path = "app/controller" }
app_exception = { path = "app/exception" }
app_filter = { path = "app/filter" }
app_mapper = { path = "app/mapper" }
app_middleware = { path = "app/middleware" }
app_model = { path = "app/model" }
app_service = { path = "app/service" }
app_utils = { path = "app/utils" }
app_view = { path = "app/view" }
init_server = { path = "init/server" }
config_business = { path = "config/business" }
config_server = { path = "config/server" }
config_server_manager = { path = "config/server_manager" }
plugin_server_manager = { path = "plugin/server_manager" }

[dependencies]
hyperlane.workspace = true
app_aspect.workspace = true
app_controller.workspace = true
app_exception.workspace = true
app_filter.workspace = true
app_mapper.workspace = true
app_middleware.workspace = true
app_model.workspace = true
app_service.workspace = true
app_utils.workspace = true
app_view.workspace = true
config_business.workspace = true
config_server.workspace = true
config_server_manager.workspace = true
init_server.workspace = true
plugin_server_manager.workspace = true

[profile.dev]
incremental = true
opt-level = 1
lto = false
panic = "unwind"
debug = true
codegen-units = 16
strip = "none"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
