[package]
name = "hyperlane-quick-start"
version = "1.0.0"
edition = "2024"
authors = ["ltpp-universe <root@ltpp.vip>"] 
license = "MIT"
description = """Hyperlane is a lightweight and high-performance Rust HTTP server library designed to simplify network service development. It supports HTTP request parsing, response building, and TCP communication, making it ideal for building modern web services. Additionally, it provides support for request and response middleware, WebSocket, and Server-Sent Events (SSE), enabling flexible and efficient real-time communication. Built with pure Rust and standard library, Hyperlane offers true cross-platform compatibility across Windows, Linux and macOS, with the same API experience on all platforms, powered by Tokio's async runtime for seamless networking without platform-specific dependencies."""
keywords = ["http", "request", "response", "tcp", "cross-platform"]
repository = "https://github.com/ltpp-universe/hyperlane-quick-start.git"
categories = ["network-programming", "web-programming"]
exclude = [
    "target",
    "Cargo.lock",
    "logs",
    ".github",
    "**/*.pid",
    "**/*.log",
    "logs"
]

[workspace]
members = [
    "app",
    "config",
    "init",
    "plugin",
    "utils",
]

[workspace.dependencies]
hyperlane = "4.94.0"
app = { path = "app" }
config = { path = "config" }
init = { path = "init" }
plugin = { path = "plugin" }
utils = { path = "utils" }

[dependencies]
hyperlane.workspace = true
app.workspace = true
config.workspace = true
init.workspace = true
plugin.workspace = true
utils.workspace = true

[patch.crates-io]
app = { path = "app", version = "0.1.0" }
config = { path = "config", version = "0.1.0"  }
init = { path = "init", version = "0.1.0"  }
plugin = { path = "plugin", version = "0.1.0"  }
utils = { path = "utils", version = "0.1.0"  }

[profile.dev]
incremental = true
opt-level = 1
lto = false
panic = "unwind"
debug = true
codegen-units = 16
strip = "none"

[profile.release]
incremental = false
opt-level = 3
lto = true
panic = "unwind"
debug = false
codegen-units = 1
strip = "debuginfo"
