[package]
name = "app_middleware"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
hyperlane.workspace = true
config_business.workspace = true
plugin_server_manager.workspace = true
