[package]
name = "init_server"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
hyperlane.workspace = true
config_business.workspace = true
config_server.workspace = true
plugin_server_manager.workspace = true
app_controller.workspace = true
app_middleware.workspace = true
