[package]
name = "init_server"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
hyperlane.workspace = true
app.workspace = true
config.workspace = true
plugin.workspace = true
