[package]
name = "app"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"

[dependencies]
hyperlane = { workspace = true }
config = { workspace = true }
init = { workspace = true }
plugin = { workspace = true }
utils = { workspace = true }
