[package]
name = "app"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
hyperlane = "4.94.0"
config = { workspace = true }
plugin = { workspace = true }
utils = { workspace = true }
