[package]
name = "app"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
app_aspect = { path = "aspect" }
app_controller = { path = "controller" }
app_exception = { path = "exception" }
app_filter = { path = "filter" }
app_mapper = { path = "mapper" }
app_middleware = { path = "middleware" }
app_model = { path = "model" }
app_service = { path = "service" }
app_utils = { path = "utils" }
app_view = { path = "view" }
