[package]
name = "config"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
config_server = { path = "server" }
config_business = { path = "business" }
config_server_manager = { path = "server_manager" }
