[package]
name = "hyperlane_config"
version = "0.1.0"
edition = "2024"

[lib]
path = "lib.rs"

[dependencies]
hyperlane_config_server = { path = "server" }
hyperlane_config_business = { path = "business" }
hyperlane_config_server_manager = { path = "server_manager" }
